"""Initial migration

Revision ID: c8c79ce90541
Revises: 
Create Date: 2024-07-23 00:13:33.097429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c79ce90541'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status_code_distribution', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('proxy_performance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey')
    )
    op.create_index('ix_test_results_test_id', 'test_results', ['test_id'], unique=True)
    op.create_index('ix_test_results_id', 'test_results', ['id'], unique=False)
    op.create_index('ix_test_results_config_id', 'test_results', ['config_id'], unique=False)
    op.create_table('test_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payload_template', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dynamic_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('num_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concurrency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('use_proxies', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('proxy_rotation_strategy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_configs_pkey')
    )
    op.create_index('ix_test_configs_name', 'test_configs', ['name'], unique=False)
    op.create_index('ix_test_configs_id', 'test_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_configs_id', table_name='test_configs')
    op.drop_index('ix_test_configs_name', table_name='test_configs')
    op.drop_table('test_configs')
    op.drop_index('ix_test_results_config_id', table_name='test_results')
    op.drop_index('ix_test_results_id', table_name='test_results')
    op.drop_index('ix_test_results_test_id', table_name='test_results')
    op.drop_table('test_results')
    # ### end Alembic commands ###
